/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  devopsSidebar: [
    {
      type: 'link',
      label: '☰ Goto ❯  BharatOS',
      href: '/',
      className: 'sidebar-nav-link',
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
